version: '3.1'

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/:/data/
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
